"""
<> Big O: O(n^2)
In this task, you are required to implement a function called print_items(n).

This function takes one integer argument, n, and prints out a pair of numbers (i, j) for every possible combination
of i and j in the range of 0 up to but not including n.

Each pair (i, j) is printed on a new line. i and j iterate over the range independently, so every combination of i
and j in the range should be printed.

The output of the function should be a series of pairs, printed one after the other, each on a new line. The pairs
should be printed in the order that they are generated by the nested loops."""


def print_items(n):
    for i in range(n):
        for j in range(n):
            print(i, j)


print_items(10)

"""def print_items(n):: This line defines a function named print_items that takes one input argument, 
n. This function is going to print pairs of numbers, and n tells the function how many pairs to print.

for i in range(n):: The for loop starts here. This loop will go from 0 up to, but not including, n. Each number it 
generates will be temporarily stored in the variable i.

for j in range(n):: Within the first loop, we start another for loop. This loop will also go from 0 to n - 1, 
and each number will be temporarily stored in the variable j.

print(i,j): This line is inside the second loop, which means it will be executed n times for each value of i. It 
prints the current values of i and j as a pair.

So, this function basically generates all possible pairs of numbers where both numbers are between 0 and n - 1, 
inclusive."""
