"""<> Big O: O(n)
Implement a Python function called print_items.

This function should take a single integer as an argument and print out a sequence of numbers from 0 up to,
but not including, the provided integer.

The function should use a for loop and Python's built-in range function to generate the sequence of numbers.

The function signature should be: def print_items(n):"""


def print_items(n):
    for i in range(n):
        print(i)


print_items(10)


""" def print_items(n): - Here, we're defining a function named print_items that takes one parameter, n.

for i in range(n): - This is a for loop. It will iterate over a sequence of numbers generated by the function range(
n). The range(n) function generates a sequence of numbers from 0 up to but not including n. For each iteration, 
i takes the next value in this sequence.

print(i) - This is a function call to print, which outputs the current value of i to the console.

print_items(10) - This is a call to the function print_items with the argument 10. This will result in the function 
running its code (the loop) with n being 10, and so it will print numbers from 0 up to but not including 10.

So, in essence, this code prints out the sequence of numbers from 0 to 9.
 """
